// 
// StickFrame Event Bus Enums and Constants
// 

export const EVENT_TYPES = {
  LEAD_CRIADO: 'LEAD_CRIADO',
  LEAD_SCORE_ALTERADO: 'LEAD_SCORE_ALTERADO',
  ORCAMENTO_ENVIADO: 'ORCAMENTO_ENVIADO',
  ORCAMENTO_VISUALIZADO: 'ORCAMENTO_VISUALIZADO',
  CONTRATO_ASSINADO: 'CONTRATO_ASSINADO',
  PROJETO_INICIADO: 'PROJETO_INICIADO',
  IFC_IMPORTADO: 'IFC_IMPORTADO',
  CORTE_GERADO: 'CORTE_GERADO',
  COMPRA_REALIZADA: 'COMPRA_REALIZADA',
  MATERIAL_RECEBIDO: 'MATERIAL_RECEBIDO',
  OBRA_INICIADA: 'OBRA_INICIADA',
  FOTO_DIARIA: 'FOTO_DIARIA',
  RDO_CRIADO: 'RDO_CRIADO',
  MEDICAO_APROVADA: 'MEDICAO_APROVADA',
  ENTREGA_REALIZADA: 'ENTREGA_REALIZADA',
  GARANTIA_INICIADA: 'GARANTIA_INICIADA'
};

export const ORIGIN_MODULES = {
  CRM: 'CRM',
  ORCAMENTOS: 'ORCAMENTOS',
  BIM: 'BIM',
  PORTAL: 'PORTAL',
  FINANCEIRO: 'FINANCEIRO',
  OBRAS: 'OBRAS',
  SUPRIMENTOS: 'SUPRIMENTOS',
  IA: 'IA',
  CALCULADORA: 'CALCULADORA'
};

export const VISIBILITY_LEVELS = {
  INTERNO: 'INTERNO',
  COMERCIAL: 'COMERCIAL',
  CLIENTE: 'CLIENTE',
  PUBLICO: 'PUBLICO'
};
